### ISSUE TITLE
سایت znucomputer

### ISSUE THREAD

**Issue by ALIREZA-BIGDELI** [AsadiAhmad/AsadiAhmad#2]
سلام آقای اسدی
وقتتون بخیر
اول که یه تشکر ویژه کنم بابت سایت فوق العاده تون...🙏🏻

من داشتم ویدیوهای طراحی الگوریتم رو از سایتتون میدیدم. بعد از یکی دو ساعت اومدم ادامه ش رو ببینم که سایت بالا نیومد. ۴ دی هم امتحان دارم😢

چون ریپو سایت رو داخل گیت هابتون گذاشته بودید، خواستم از اون طریق لینک هارو بردارم که متوجه شدم توی دیتابیس ذخیره کردید و...

خواستم ببینم اگه زمان میبره تا سایت اوکی بشه، اگه امکانش باشه لینک ویدیو هارو برام بفرستید🙏🏻
ممنون

**Comment by AsadiAhmad** [comment]
znucomputer website will be alive at znuce.ahmadasadi.ir
be patient
